# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2828f2196e8b737f27e8851f9df92fd3c3f0b3301950335079d5a835cf2bb859aa4817c9cb6b0ffe5d38b4e552a5e8295a99971f26fb72107eadf290e55385

test:
  secret_key_base: 630840726904f0d9bcd338b52f45f859648be71511554bed3c56c4936eab24514bb88dc5f45d0bd806c8f156a07f9a3bfcef012f6919b97e12a7a6c88a87ae2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
